version: '3.8'

services:
  postgres_database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: U9oQc10UY@*8
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      DATABASE_HOST: postgres_database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: U9oQc10UY@*8
      DATABASE_NAME: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres_database

volumes:
  postgres_data:
